name: Bundler
# Currently we run in two situations:
on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-22.04
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    name: bundler
    steps:
      - run: apt-get update && apt-get install -y nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - uses: https://codeberg.org/TeXhackse/ptxtools-Demo-Wrapper@main
        with:
          module: OTHR-CI
      - run: ls -lah build/overleaf-bundles
      - name: Archive bundles
        # temporary fork since actions/upload-artifact@v4 is not working it not on github
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        # uses: github/upload-artifact@v4
        with:
          name: Bundles
          path: "build/overleaf-bundles/*.zip"
          retention-days: 21
      - name: move bundles
        run: mkdir -p overleaf-bundles && mv build/overleaf-bundles/*.zip overleaf-bundles/.
      - uses: https://github.com/crazy-max/ghaction-github-pages@v4
        # only publish pdf from main branch
        if: github.ref == 'refs/heads/main'
        with:
          target_branch: overleaf-bundles
          build_dir: overleaf-bundles
          domain: codeberg.org
          commit_message: Publish Output Bundles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
