name: Test document

# Currently we run in two situations:
on:
  push:
  pull_request:

jobs:
  test-document-iot:
    if: forgejo.ref != 'refs/heads/main'
    # tests using full TeX Live images provided by Island of TeX: https://gitlab.com/islandoftex/images/texlive
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: ["TL2023-historic", "TL2024-historic", "latest"]
        # engine: [pdflatex, xelatex, lualatex]
    name: "Test Suite Linux (IoT) on ${{ matrix.image }}"
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:${{ matrix.image }}
    steps:
      - name: install NodeJS
        run: apt-get update && apt-get install -y nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: l3build doc
        run: l3build doc
        continue-on-error: true

  test-other-examples:
    if: forgejo.ref != 'refs/heads/main'
    # tests using full TeX Live images provided by Island of TeX: https://gitlab.com/islandoftex/images/texlive
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: ["TL2023-historic", "TL2024-historic", "latest"]
    name: "Test other example documents on ${{ matrix.image }}"
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:${{ matrix.image }}
    steps:
      - name: install NodeJS
        run: apt-get update && apt-get install -y nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name install the bundle
        run: l3build install
      - name: test example
        run: make examples
        continue-on-error: true
