
.PHONY: Bachelorarbeit Bibliotheksbestellung EinladungFakultaetsrat Memo Plakat Praesentation ProtokollFakultaetsrat Studiengangsprofil Testbrief

all: Abschlussarbeit Bachelorarbeit Bibliotheksbestellung EinladungFakultaetsrat Memo Plakat Praesentation ProtokollFakultaetsrat Studiengangsprofil Testbrief

Abschlussarbeit:
	cd Abschlussarbeit && make

Projektbericht:
	cd Projektbericht && make

Bibliotheksbestellung:
	cd Bibliotheksbestellung && make

EinladungFakultaetsrat:
	cd EinladungFakultaetsrat && make

Memo:
	cd Memo && make

Plakat:
	cd Plakat && make

Praesentation:
	cd Praesentation && make

ProtokollFakultaetsrat:
	cd ProtokollFakultätsrat && make

Studiengangsprofil:
	cd Studiengangsprofil && make

Testbrief:
	cd Testbrief && make
