
.PHONY:  Abschlussarbeit Projektbericht Testbrief

all: Abschlussarbeit Projektbericht Testbrief

Abschlussarbeit:
	cd Abschlussarbeit && make

Projektbericht:
	cd Projektbericht && make

Testbrief:
	cd Testbrief && make
