%
% OTHRbook -- LaTeX using the Corporate Design of OTH Regensburg
% ----------------------------------------------------------------------------
%
%  Copyright (C) 2015-2025 Michael Nietmetz <michael.niemetz@oth-regensburg.de>
%                 and the OTH Regensburg-LaTeX-Team
%
% ============================================================================
% This work may be distributed and/or modified under the
% conditions of the LaTeX Project Public License, either version 1.3c
% of this license or (at your option) any later version.
% The latest version of this license is in
% http://www.latex-project.org/lppl.txt
% and version 1.3c or later is part of all distributions of LaTeX
% version 2008/05/04 or later.
%
% This work has the LPPL maintenance status `maintained'.
%
% The Current Maintainers of this work are
%   Michael Niemetz <michael.niemetz@oth-regensburg.de>
%
% The development repository can be found at
% https://codeberg.org/OTH-Regensburg/OTHRegensburg-LaTeX
% Please use the issue tracker for feedback!
% ============================================================================
\ProvidesClass{OTHRbook}

\LoadClassWithOptions{scrbook}
\RequirePackage{OTHR}
\RequirePackage{OTHR_clscommons}
